      // doc3.contentWindow.scrollTo(0,2000)
      // doc2.contentWindow.scrollTo(0,1000)
      // let f1Acc = new WinAccount(doc1.contentWindow)
      // let f1Ch = new Channel()
      // f1Acc.setPubChannel(f1Ch)
      // let f2Acc = new WinAccount(doc2.contentWindow)
      // let f2Ch = new Channel()
      // f2Acc.setPubChannel(f2Ch)
      // let f3Acc = new WinAccount(doc3.contentWindow)
      // let f3Ch = new Channel()
      // f3Acc.setPubChannel(f3Ch)
      // console.log(f2Ch)
      // f1Acc.setSubChannel(f2Ch)
      // f1Acc.setScrollFunction(f2Ch, ScrollFuncs["relSpring"])
      // console.log(f2Ch)
      // f1Acc.setSubChannel(f3Ch)
      // f1Acc.setScrollFunction(f3Ch, ScrollFuncs["relSpring"])
      
      // f2Acc.setSubChannel(f1Ch)
      // f2Acc.setScrollFunction(f1Ch, ScrollFuncs["relSpring"])
      // f2Acc.setSubChannel(f3Ch)
      // f2Acc.setScrollFunction(f3Ch, ScrollFuncs["relSpring"])
      
      // f3Acc.setSubChannel(f1Ch)
      // f3Acc.setScrollFunction(f1Ch, ScrollFuncs["relSpring"])
      // f3Acc.setSubChannel(f2Ch)
      // f3Acc.setScrollFunction(f2Ch, ScrollFuncs["relSpring"])
      // console.log(f2Ch)

      // f1Acc.initialPublish()
      // f2Acc.initialPublish()
      // f3Acc.initialPublish()
      // f1Acc.startPublishing()
      // f2Acc.startPublishing()
      // f3Acc.startPublishing()